name: NoTmpContent
main: Johnmacrocraft\NoTmpContent\NoTmpContent
version: 1.0.0
api: [3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9]
load: POSTWORLD
author: Johnmacrocraft
description: Cleans your tmp folder in PocketMine-MP for Android!
website: https://github.com/Johnmacrocraft/NoTmpContent