name: NoTmpContent
main: Johnmacrocraft\NoTmpContent\NoTmpContent
version: 1.0.0
api: [3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12]
load: POSTWORLD
author: Johnmacrocraft
description: Cleans your tmp folder in PocketMine-MP for Android!
website: https://github.com/Johnmacrocraft/NoTmpContent